/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttperrorsHttpErrorResponse {
    /// error message
    #[serde(rename = "message")]
    pub message: String,
    /// http status code
    #[serde(rename = "statuscode")]
    pub statuscode: i64,
}

impl HttperrorsHttpErrorResponse {
    pub fn new(message: String, statuscode: i64) -> HttperrorsHttpErrorResponse {
        HttperrorsHttpErrorResponse {
            message,
            statuscode,
        }
    }
}


