/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BgpFilter {
    /// the cidr addresses that are allowed to be announced at this switch port
    #[serde(rename = "cidrs")]
    pub cidrs: Vec<String>,
    /// the virtual networks that are exposed at this switch port
    #[serde(rename = "vnis", skip_serializing_if = "Option::is_none")]
    pub vnis: Option<Vec<String>>,
}

impl V1BgpFilter {
    pub fn new(cidrs: Vec<String>) -> V1BgpFilter {
        V1BgpFilter {
            cidrs,
            vnis: None,
        }
    }
}


