/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BootInfo {
    /// the bootloader ID
    #[serde(rename = "bootloaderid")]
    pub bootloaderid: String,
    /// the cmdline
    #[serde(rename = "cmdline")]
    pub cmdline: String,
    /// the ID of the current image
    #[serde(rename = "image_id")]
    pub image_id: String,
    /// the initrd image
    #[serde(rename = "initrd")]
    pub initrd: String,
    /// the kernel
    #[serde(rename = "kernel")]
    pub kernel: String,
    /// the partition containing the OS
    #[serde(rename = "os_partition")]
    pub os_partition: String,
    /// the primary disk
    #[serde(rename = "primary_disk")]
    pub primary_disk: String,
}

impl V1BootInfo {
    pub fn new(bootloaderid: String, cmdline: String, image_id: String, initrd: String, kernel: String, os_partition: String, primary_disk: String) -> V1BootInfo {
        V1BootInfo {
            bootloaderid,
            cmdline,
            image_id,
            initrd,
            kernel,
            os_partition,
            primary_disk,
        }
    }
}


