/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineNicExtended {
    /// the mac address of this network interface
    #[serde(rename = "mac")]
    pub mac: String,
    /// the name of this network interface
    #[serde(rename = "name")]
    pub name: String,
    /// the neighbors visible to this network interface
    #[serde(rename = "neighbors")]
    pub neighbors: Vec<crate::models::V1MachineNicExtended>,
}

impl V1MachineNicExtended {
    pub fn new(mac: String, name: String, neighbors: Vec<crate::models::V1MachineNicExtended>) -> V1MachineNicExtended {
        V1MachineNicExtended {
            mac,
            name,
            neighbors,
        }
    }
}


