/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// V1MachineIpmi : The IPMI connection data



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineIpmi {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "bmcversion")]
    pub bmcversion: String,
    #[serde(rename = "fru")]
    pub fru: crate::models::V1MachineFru,
    #[serde(rename = "interface")]
    pub interface: String,
    #[serde(rename = "mac")]
    pub mac: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl V1MachineIpmi {
    /// The IPMI connection data
    pub fn new(address: String, bmcversion: String, fru: crate::models::V1MachineFru, interface: String, mac: String, password: String, user: String) -> V1MachineIpmi {
        V1MachineIpmi {
            address,
            bmcversion,
            fru,
            interface,
            mac,
            password,
            user,
        }
    }
}


