/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineAllocationNetwork {
    /// will automatically acquire an ip in this network if set to true, default is true
    #[serde(rename = "autoacquire")]
    pub autoacquire: bool,
    /// the id of the network that this machine will be placed in
    #[serde(rename = "networkid")]
    pub networkid: String,
}

impl V1MachineAllocationNetwork {
    pub fn new(autoacquire: bool, networkid: String) -> V1MachineAllocationNetwork {
        V1MachineAllocationNetwork {
            autoacquire,
            networkid,
        }
    }
}


