/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// V1MachineFru : The Field Replaceable Unit data



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineFru {
    /// the board mfg
    #[serde(rename = "board_mfg", skip_serializing_if = "Option::is_none")]
    pub board_mfg: Option<String>,
    /// the board mfg serial
    #[serde(rename = "board_mfg_serial", skip_serializing_if = "Option::is_none")]
    pub board_mfg_serial: Option<String>,
    /// the board part number
    #[serde(rename = "board_part_number", skip_serializing_if = "Option::is_none")]
    pub board_part_number: Option<String>,
    /// the chassis part number
    #[serde(rename = "chassis_part_number", skip_serializing_if = "Option::is_none")]
    pub chassis_part_number: Option<String>,
    /// the chassis part serial
    #[serde(rename = "chassis_part_serial", skip_serializing_if = "Option::is_none")]
    pub chassis_part_serial: Option<String>,
    /// the product manufacturer
    #[serde(rename = "product_manufacturer", skip_serializing_if = "Option::is_none")]
    pub product_manufacturer: Option<String>,
    /// the product part number
    #[serde(rename = "product_part_number", skip_serializing_if = "Option::is_none")]
    pub product_part_number: Option<String>,
    /// the product serial
    #[serde(rename = "product_serial", skip_serializing_if = "Option::is_none")]
    pub product_serial: Option<String>,
}

impl V1MachineFru {
    /// The Field Replaceable Unit data
    pub fn new() -> V1MachineFru {
        V1MachineFru {
            board_mfg: None,
            board_mfg_serial: None,
            board_part_number: None,
            chassis_part_number: None,
            chassis_part_serial: None,
            product_manufacturer: None,
            product_part_number: None,
            product_serial: None,
        }
    }
}


