/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineHardwareExtended {
    /// the number of cpu cores
    #[serde(rename = "cpu_cores")]
    pub cpu_cores: i64,
    /// the list of block devices of this machine
    #[serde(rename = "disks")]
    pub disks: Vec<crate::models::V1MachineBlockDevice>,
    /// the total memory of the machine
    #[serde(rename = "memory")]
    pub memory: i64,
    /// the list of network interfaces of this machine with extended information
    #[serde(rename = "nics")]
    pub nics: Vec<crate::models::V1MachineNicExtended>,
}

impl V1MachineHardwareExtended {
    pub fn new(cpu_cores: i64, disks: Vec<crate::models::V1MachineBlockDevice>, memory: i64, nics: Vec<crate::models::V1MachineNicExtended>) -> V1MachineHardwareExtended {
        V1MachineHardwareExtended {
            cpu_cores,
            disks,
            memory,
            nics,
        }
    }
}


