/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineRecentProvisioningEvents {
    /// the amount of incomplete provisioning cycles in the event container
    #[serde(rename = "incomplete_provisioning_cycles")]
    pub incomplete_provisioning_cycles: String,
    /// the time where the last event was received
    #[serde(rename = "last_event_time", skip_serializing_if = "Option::is_none")]
    pub last_event_time: Option<String>,
    /// the log of recent machine provisioning events
    #[serde(rename = "log")]
    pub log: Vec<crate::models::V1MachineProvisioningEvent>,
}

impl V1MachineRecentProvisioningEvents {
    pub fn new(incomplete_provisioning_cycles: String, log: Vec<crate::models::V1MachineProvisioningEvent>) -> V1MachineRecentProvisioningEvents {
        V1MachineRecentProvisioningEvents {
            incomplete_provisioning_cycles,
            last_event_time: None,
            log,
        }
    }
}


