/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineAbortReinstallRequest {
    /// indicates whether the primary disk is already wiped
    #[serde(rename = "primary_disk_wiped")]
    pub primary_disk_wiped: bool,
}

impl V1MachineAbortReinstallRequest {
    pub fn new(primary_disk_wiped: bool) -> V1MachineAbortReinstallRequest {
        V1MachineAbortReinstallRequest {
            primary_disk_wiped,
        }
    }
}


