/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineFinalizeAllocationRequest {
    /// the bootloader ID
    #[serde(rename = "bootloaderid")]
    pub bootloaderid: String,
    /// the cmdline
    #[serde(rename = "cmdline")]
    pub cmdline: String,
    /// the console password which was generated while provisioning
    #[serde(rename = "console_password")]
    pub console_password: String,
    /// the initrd image
    #[serde(rename = "initrd")]
    pub initrd: String,
    /// the kernel
    #[serde(rename = "kernel")]
    pub kernel: String,
    /// the partition that has the OS installed
    #[serde(rename = "ospartition")]
    pub ospartition: String,
    /// the device name of the primary disk
    #[serde(rename = "primarydisk")]
    pub primarydisk: String,
}

impl V1MachineFinalizeAllocationRequest {
    pub fn new(bootloaderid: String, cmdline: String, console_password: String, initrd: String, kernel: String, ospartition: String, primarydisk: String) -> V1MachineFinalizeAllocationRequest {
        V1MachineFinalizeAllocationRequest {
            bootloaderid,
            cmdline,
            console_password,
            initrd,
            kernel,
            ospartition,
            primarydisk,
        }
    }
}


