/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// V1MachineNetwork : prefixes that are reachable within this network



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineNetwork {
    /// ASN number for this network in the bgp configuration
    #[serde(rename = "asn")]
    pub asn: i64,
    /// the destination prefixes of this network
    #[serde(rename = "destinationprefixes")]
    pub destinationprefixes: Vec<String>,
    /// the ip addresses of the allocated machine in this vrf
    #[serde(rename = "ips")]
    pub ips: Vec<String>,
    /// if set to true, packets leaving this network get masqueraded behind interface ip
    #[serde(rename = "nat")]
    pub nat: bool,
    /// the networkID of the allocated machine in this vrf
    #[serde(rename = "networkid")]
    pub networkid: String,
    /// the network type, types can be looked up in the network package of metal-lib
    #[serde(rename = "networktype")]
    pub networktype: String,
    /// the prefixes of this network
    #[serde(rename = "prefixes")]
    pub prefixes: Vec<String>,
    /// indicates whether this network is the private network of this machine
    #[serde(rename = "private")]
    pub private: bool,
    /// if set to true, this network can be used for underlay communication
    #[serde(rename = "underlay")]
    pub underlay: bool,
    /// the vrf of the allocated machine
    #[serde(rename = "vrf")]
    pub vrf: i64,
}

impl V1MachineNetwork {
    /// prefixes that are reachable within this network
    pub fn new(asn: i64, destinationprefixes: Vec<String>, ips: Vec<String>, nat: bool, networkid: String, networktype: String, prefixes: Vec<String>, private: bool, underlay: bool, vrf: i64) -> V1MachineNetwork {
        V1MachineNetwork {
            asn,
            destinationprefixes,
            ips,
            nat,
            networkid,
            networktype,
            prefixes,
            private,
            underlay,
            vrf,
        }
    }
}


