/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// V1MachineBios : The bios version



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineBios {
    /// the bios date
    #[serde(rename = "date")]
    pub date: String,
    /// the bios vendor
    #[serde(rename = "vendor")]
    pub vendor: String,
    /// the bios version
    #[serde(rename = "version")]
    pub version: String,
}

impl V1MachineBios {
    /// The bios version
    pub fn new(date: String, vendor: String, version: String) -> V1MachineBios {
        V1MachineBios {
            date,
            vendor,
            version,
        }
    }
}


