/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineNic {
    /// the mac address of this network interface
    #[serde(rename = "mac")]
    pub mac: String,
    /// the name of this network interface
    #[serde(rename = "name")]
    pub name: String,
}

impl V1MachineNic {
    pub fn new(mac: String, name: String) -> V1MachineNic {
        V1MachineNic {
            mac,
            name,
        }
    }
}


