/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MachineProvisioningEvent {
    /// the event emitted by the machine
    #[serde(rename = "event")]
    pub event: String,
    /// an additional message to add to the event
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// the time that this event was received
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl V1MachineProvisioningEvent {
    pub fn new(event: String) -> V1MachineProvisioningEvent {
        V1MachineProvisioningEvent {
            event,
            message: None,
            time: None,
        }
    }
}


