/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NetworkAllocateRequest {
    /// a description for this entity
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// the destination prefixes of this network
    #[serde(rename = "destinationprefixes", skip_serializing_if = "Option::is_none")]
    pub destinationprefixes: Option<Vec<String>>,
    /// free labels that you associate with this network.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// a readable name for this entity
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// if set to true, packets leaving this network get masqueraded behind interface ip
    #[serde(rename = "nat", skip_serializing_if = "Option::is_none")]
    pub nat: Option<bool>,
    /// the partition this network belongs to
    #[serde(rename = "partitionid", skip_serializing_if = "Option::is_none")]
    pub partitionid: Option<String>,
    /// the project id this network belongs to, can be empty if globally available
    #[serde(rename = "projectid", skip_serializing_if = "Option::is_none")]
    pub projectid: Option<String>,
    /// marks a network as shareable.
    #[serde(rename = "shared", skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,
}

impl V1NetworkAllocateRequest {
    pub fn new() -> V1NetworkAllocateRequest {
        V1NetworkAllocateRequest {
            description: None,
            destinationprefixes: None,
            labels: None,
            name: None,
            nat: None,
            partitionid: None,
            projectid: None,
            shared: None,
        }
    }
}


