/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NetworkFindRequest {
    #[serde(rename = "destinationprefixes", skip_serializing_if = "Option::is_none")]
    pub destinationprefixes: Option<Vec<String>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nat", skip_serializing_if = "Option::is_none")]
    pub nat: Option<bool>,
    #[serde(rename = "parentnetworkid", skip_serializing_if = "Option::is_none")]
    pub parentnetworkid: Option<String>,
    #[serde(rename = "partitionid", skip_serializing_if = "Option::is_none")]
    pub partitionid: Option<String>,
    #[serde(rename = "prefixes", skip_serializing_if = "Option::is_none")]
    pub prefixes: Option<Vec<String>>,
    #[serde(rename = "privatesuper", skip_serializing_if = "Option::is_none")]
    pub privatesuper: Option<bool>,
    #[serde(rename = "projectid", skip_serializing_if = "Option::is_none")]
    pub projectid: Option<String>,
    #[serde(rename = "underlay", skip_serializing_if = "Option::is_none")]
    pub underlay: Option<bool>,
    #[serde(rename = "vrf", skip_serializing_if = "Option::is_none")]
    pub vrf: Option<i64>,
}

impl V1NetworkFindRequest {
    pub fn new() -> V1NetworkFindRequest {
        V1NetworkFindRequest {
            destinationprefixes: None,
            id: None,
            labels: None,
            name: None,
            nat: None,
            parentnetworkid: None,
            partitionid: None,
            prefixes: None,
            privatesuper: None,
            projectid: None,
            underlay: None,
            vrf: None,
        }
    }
}


