/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PartitionUpdateRequest {
    #[serde(rename = "bootconfig", skip_serializing_if = "Option::is_none")]
    pub bootconfig: Option<crate::models::V1PartitionBootConfiguration>,
    /// a description for this entity
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// the unique ID of this entity
    #[serde(rename = "id")]
    pub id: String,
    /// the address to the management service of this partition
    #[serde(rename = "mgmtserviceaddress", skip_serializing_if = "Option::is_none")]
    pub mgmtserviceaddress: Option<String>,
    /// a readable name for this entity
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1PartitionUpdateRequest {
    pub fn new(id: String) -> V1PartitionUpdateRequest {
        V1PartitionUpdateRequest {
            bootconfig: None,
            description: None,
            id,
            mgmtserviceaddress: None,
            name: None,
        }
    }
}


