/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1Quota {
    #[serde(rename = "quota", skip_serializing_if = "Option::is_none")]
    pub quota: Option<i64>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i64>,
}

impl V1Quota {
    pub fn new() -> V1Quota {
        V1Quota {
            quota: None,
            used: None,
        }
    }
}


