/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SwitchNotifyRequest {
    #[serde(rename = "error")]
    pub error: String,
    /// the duration of the switch synchronization
    #[serde(rename = "sync_duration")]
    pub sync_duration: i64,
}

impl V1SwitchNotifyRequest {
    pub fn new(error: String, sync_duration: i64) -> V1SwitchNotifyRequest {
        V1SwitchNotifyRequest {
            error,
            sync_duration,
        }
    }
}


