/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SizeConstraintMatchingLog {
    #[serde(rename = "constraint")]
    pub constraint: crate::models::V1SizeConstraint,
    /// a string represention of the matching condition
    #[serde(rename = "log")]
    pub log: String,
    /// indicates whether the constraint matched or not
    #[serde(rename = "match")]
    pub _match: bool,
}

impl V1SizeConstraintMatchingLog {
    pub fn new(constraint: crate::models::V1SizeConstraint, log: String, _match: bool) -> V1SizeConstraintMatchingLog {
        V1SizeConstraintMatchingLog {
            constraint,
            log,
            _match,
        }
    }
}


