/*
 * metal-api
 *
 * API to manage and control plane resources like machines, switches, operating system images, machine sizes, networks, IP addresses and more
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ulrich.schreiner@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SwitchSync {
    /// the duration that lat switch sync took
    #[serde(rename = "duration")]
    pub duration: i64,
    /// shows the error occurred during the sync
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// point in time when the last switch sync happened
    #[serde(rename = "time")]
    pub time: String,
}

impl V1SwitchSync {
    pub fn new(duration: i64, time: String) -> V1SwitchSync {
        V1SwitchSync {
            duration,
            error: None,
            time,
        }
    }
}


